# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true

inject:
  head:
  bottom:
    - <div class="aplayer no-destroy" data-id="317661322" data-server="netease" data-type="playlist" data-mini="true" data-autoplay="true" data-lrcType="-1"> </div>


pjax:
 enable: true
 exclude:

 